### ISSUE TITLE
ERROR in ./node_modules/uiw-iconfont/fonts/w-icon.json Module parse failed: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {"a...' You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by Mr-zsy** [uiwjs/react-code-preview#1]
How can i deall with it?

**Comment by jaywcjlove** [comment]
@Mr-zsy Can I see your project engineering debugging?

**Comment by Mr-zsy** [comment]
is this？
```
ERROR in ./node_modules/uiw-iconfont/fonts/w-icon.json
Module parse failed: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {"a...'
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {"a...'
    at JSON.parse (<anonymous>)
    at parseJson (/Users/xxx/Desktop/demo/QA/node_modules/json-parse-better-errors/index.js:7:17)
    at JsonParser.parse (/Users/xxx/Desktop/demo/QA/node_modules/webpack/lib/JsonParser.js:16:16)
    at doBuild.err (/Users/xxx/Desktop/demo/QA/node_modules/webpack/lib/NormalModule.js:460:32)
    at runLoaders (/Users/xxx/Desktop/demo/QA/node_modules/webpack/lib/NormalModule.js:342:12)
    at /Users/xxx/Desktop/demo/QA/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/xxx/Desktop/demo/QA/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/xxx/Desktop/demo/QA/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/xxx/Desktop/demo/QA/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/xxx/Desktop/demo/QA/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
`````

**Comment by jaywcjlove** [comment]
@Mr-zsy  你的工程不支持加载 JSON 格式文件？webpack 默认配置 [`json-loader`](https://webpack.docschina.org/loaders/json-loader) 这个似乎要排查一下你的工程呢

**Comment by Mr-zsy** [comment]
谢谢大哥，我使用的`webpack4`，在配置里面配置了`json-loader`，去掉就好了

**Comment by jaywcjlove** [comment]
@Mr-zsy 不用客气欢迎来个 star
